//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.08 at 10:53:14 PM IST 
//


package com.myschool.schoolAccess;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.myschool.schoolAccess package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.myschool.schoolAccess
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchoolAccess }
     * 
     */
    public SchoolAccess createSchoolAccess() {
        return new SchoolAccess();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement }
     * 
     */
    public SchoolAccess.FunctionalManagement createSchoolAccessFunctionalManagement() {
        return new SchoolAccess.FunctionalManagement();
    }

    /**
     * Create an instance of {@link SchoolAccess.ConfigurationManagement }
     * 
     */
    public SchoolAccess.ConfigurationManagement createSchoolAccessConfigurationManagement() {
        return new SchoolAccess.ConfigurationManagement();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement.FmAdministrator }
     * 
     */
    public SchoolAccess.FunctionalManagement.FmAdministrator createSchoolAccessFunctionalManagementFmAdministrator() {
        return new SchoolAccess.FunctionalManagement.FmAdministrator();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement.FmLeaves }
     * 
     */
    public SchoolAccess.FunctionalManagement.FmLeaves createSchoolAccessFunctionalManagementFmLeaves() {
        return new SchoolAccess.FunctionalManagement.FmLeaves();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement.FmCommunication }
     * 
     */
    public SchoolAccess.FunctionalManagement.FmCommunication createSchoolAccessFunctionalManagementFmCommunication() {
        return new SchoolAccess.FunctionalManagement.FmCommunication();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement.FmTransportation }
     * 
     */
    public SchoolAccess.FunctionalManagement.FmTransportation createSchoolAccessFunctionalManagementFmTransportation() {
        return new SchoolAccess.FunctionalManagement.FmTransportation();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement.FmFinance }
     * 
     */
    public SchoolAccess.FunctionalManagement.FmFinance createSchoolAccessFunctionalManagementFmFinance() {
        return new SchoolAccess.FunctionalManagement.FmFinance();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement.FmLibrary }
     * 
     */
    public SchoolAccess.FunctionalManagement.FmLibrary createSchoolAccessFunctionalManagementFmLibrary() {
        return new SchoolAccess.FunctionalManagement.FmLibrary();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement.FmReports }
     * 
     */
    public SchoolAccess.FunctionalManagement.FmReports createSchoolAccessFunctionalManagementFmReports() {
        return new SchoolAccess.FunctionalManagement.FmReports();
    }

    /**
     * Create an instance of {@link SchoolAccess.FunctionalManagement.FmAvailability }
     * 
     */
    public SchoolAccess.FunctionalManagement.FmAvailability createSchoolAccessFunctionalManagementFmAvailability() {
        return new SchoolAccess.FunctionalManagement.FmAvailability();
    }

    /**
     * Create an instance of {@link SchoolAccess.ConfigurationManagement.CmAdministrator }
     * 
     */
    public SchoolAccess.ConfigurationManagement.CmAdministrator createSchoolAccessConfigurationManagementCmAdministrator() {
        return new SchoolAccess.ConfigurationManagement.CmAdministrator();
    }

    /**
     * Create an instance of {@link SchoolAccess.ConfigurationManagement.CmStaff }
     * 
     */
    public SchoolAccess.ConfigurationManagement.CmStaff createSchoolAccessConfigurationManagementCmStaff() {
        return new SchoolAccess.ConfigurationManagement.CmStaff();
    }

    /**
     * Create an instance of {@link SchoolAccess.ConfigurationManagement.CmCalendar }
     * 
     */
    public SchoolAccess.ConfigurationManagement.CmCalendar createSchoolAccessConfigurationManagementCmCalendar() {
        return new SchoolAccess.ConfigurationManagement.CmCalendar();
    }

    /**
     * Create an instance of {@link SchoolAccess.ConfigurationManagement.CmTransport }
     * 
     */
    public SchoolAccess.ConfigurationManagement.CmTransport createSchoolAccessConfigurationManagementCmTransport() {
        return new SchoolAccess.ConfigurationManagement.CmTransport();
    }

    /**
     * Create an instance of {@link SchoolAccess.ConfigurationManagement.CmFinance }
     * 
     */
    public SchoolAccess.ConfigurationManagement.CmFinance createSchoolAccessConfigurationManagementCmFinance() {
        return new SchoolAccess.ConfigurationManagement.CmFinance();
    }

    /**
     * Create an instance of {@link SchoolAccess.ConfigurationManagement.CmLibrary }
     * 
     */
    public SchoolAccess.ConfigurationManagement.CmLibrary createSchoolAccessConfigurationManagementCmLibrary() {
        return new SchoolAccess.ConfigurationManagement.CmLibrary();
    }

}
