//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 10:00:03 PM IST 
//


package com.myschool.schoolAccess;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.myschool.schoolAccess package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.myschool.schoolAccess
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest }
     * 
     */
    public SchoolLevelAccessRequest createSchoolLevelAccessRequest() {
        return new SchoolLevelAccessRequest();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement createSchoolLevelAccessRequestFunctionalManagement() {
        return new SchoolLevelAccessRequest.FunctionalManagement();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.ConfigurationManagment }
     * 
     */
    public SchoolLevelAccessRequest.ConfigurationManagment createSchoolLevelAccessRequestConfigurationManagment() {
        return new SchoolLevelAccessRequest.ConfigurationManagment();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement.FmAdministrator }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement.FmAdministrator createSchoolLevelAccessRequestFunctionalManagementFmAdministrator() {
        return new SchoolLevelAccessRequest.FunctionalManagement.FmAdministrator();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement.FmLeaves }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement.FmLeaves createSchoolLevelAccessRequestFunctionalManagementFmLeaves() {
        return new SchoolLevelAccessRequest.FunctionalManagement.FmLeaves();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement.FmCommunication }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement.FmCommunication createSchoolLevelAccessRequestFunctionalManagementFmCommunication() {
        return new SchoolLevelAccessRequest.FunctionalManagement.FmCommunication();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement.FmTransportation }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement.FmTransportation createSchoolLevelAccessRequestFunctionalManagementFmTransportation() {
        return new SchoolLevelAccessRequest.FunctionalManagement.FmTransportation();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement.FmFinance }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement.FmFinance createSchoolLevelAccessRequestFunctionalManagementFmFinance() {
        return new SchoolLevelAccessRequest.FunctionalManagement.FmFinance();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement.FmLibrary }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement.FmLibrary createSchoolLevelAccessRequestFunctionalManagementFmLibrary() {
        return new SchoolLevelAccessRequest.FunctionalManagement.FmLibrary();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement.FmReports }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement.FmReports createSchoolLevelAccessRequestFunctionalManagementFmReports() {
        return new SchoolLevelAccessRequest.FunctionalManagement.FmReports();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.FunctionalManagement.FmAvailability }
     * 
     */
    public SchoolLevelAccessRequest.FunctionalManagement.FmAvailability createSchoolLevelAccessRequestFunctionalManagementFmAvailability() {
        return new SchoolLevelAccessRequest.FunctionalManagement.FmAvailability();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.ConfigurationManagment.CmAdministrator }
     * 
     */
    public SchoolLevelAccessRequest.ConfigurationManagment.CmAdministrator createSchoolLevelAccessRequestConfigurationManagmentCmAdministrator() {
        return new SchoolLevelAccessRequest.ConfigurationManagment.CmAdministrator();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.ConfigurationManagment.CmStaff }
     * 
     */
    public SchoolLevelAccessRequest.ConfigurationManagment.CmStaff createSchoolLevelAccessRequestConfigurationManagmentCmStaff() {
        return new SchoolLevelAccessRequest.ConfigurationManagment.CmStaff();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.ConfigurationManagment.CmCalendar }
     * 
     */
    public SchoolLevelAccessRequest.ConfigurationManagment.CmCalendar createSchoolLevelAccessRequestConfigurationManagmentCmCalendar() {
        return new SchoolLevelAccessRequest.ConfigurationManagment.CmCalendar();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.ConfigurationManagment.CmTransport }
     * 
     */
    public SchoolLevelAccessRequest.ConfigurationManagment.CmTransport createSchoolLevelAccessRequestConfigurationManagmentCmTransport() {
        return new SchoolLevelAccessRequest.ConfigurationManagment.CmTransport();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.ConfigurationManagment.CmFinance }
     * 
     */
    public SchoolLevelAccessRequest.ConfigurationManagment.CmFinance createSchoolLevelAccessRequestConfigurationManagmentCmFinance() {
        return new SchoolLevelAccessRequest.ConfigurationManagment.CmFinance();
    }

    /**
     * Create an instance of {@link SchoolLevelAccessRequest.ConfigurationManagment.CmLibrary }
     * 
     */
    public SchoolLevelAccessRequest.ConfigurationManagment.CmLibrary createSchoolLevelAccessRequestConfigurationManagmentCmLibrary() {
        return new SchoolLevelAccessRequest.ConfigurationManagment.CmLibrary();
    }

}
