//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.08 at 10:53:14 PM IST 
//


package com.myschool.schoolAccess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configurationManagement">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cmAdministrator">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cmAdministratorAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmUserRole" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmClass" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmSection" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmSubjects" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="cmStaff">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cmStaffAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmAppointmentType" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmLeaveSructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="cmCalendar">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cmCalendarAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmSchoolCalendar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmClassCalendar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="cmTransport">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cmTransportAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmDriver" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmVehicle" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmRoute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="cmFinance">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cmFinanceAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmTuitionFeeStructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmOtherFeeStructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="cmLibrary">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cmLibraryAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmLibraryBooksCategory" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="cmLibraryBooksEntry" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="functionalManagement">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fmAdministrator">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fmAdministratorAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmUser" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmStaff" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmStudent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmRollNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fmLeaves">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fmLeavesAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmStudentLeaves" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmStaffLeaves" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fmCommunication">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fmCommunicationAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmSchedule" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmHolidays" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmSms" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fmTransportation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fmTransportationAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmTransportationRoute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fmFinance">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fmFinanceAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmTuitionFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmOtherFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fmLibrary">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fmLibraryAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmBooks" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fmReports">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fmReportsAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmStudentReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmStaffReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmClassReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmSchoolReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fmAvailability">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fmAvailabilityAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="fmAvailabilityCheck" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configurationManagement",
    "functionalManagement"
})
@XmlRootElement(name = "schoolAccess")
public class SchoolAccess {

    @XmlElement(required = true)
    protected SchoolAccess.ConfigurationManagement configurationManagement;
    @XmlElement(required = true)
    protected SchoolAccess.FunctionalManagement functionalManagement;

    /**
     * Gets the value of the configurationManagement property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolAccess.ConfigurationManagement }
     *     
     */
    public SchoolAccess.ConfigurationManagement getConfigurationManagement() {
        return configurationManagement;
    }

    /**
     * Sets the value of the configurationManagement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolAccess.ConfigurationManagement }
     *     
     */
    public void setConfigurationManagement(SchoolAccess.ConfigurationManagement value) {
        this.configurationManagement = value;
    }

    /**
     * Gets the value of the functionalManagement property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolAccess.FunctionalManagement }
     *     
     */
    public SchoolAccess.FunctionalManagement getFunctionalManagement() {
        return functionalManagement;
    }

    /**
     * Sets the value of the functionalManagement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolAccess.FunctionalManagement }
     *     
     */
    public void setFunctionalManagement(SchoolAccess.FunctionalManagement value) {
        this.functionalManagement = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cmAdministrator">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cmAdministratorAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmUserRole" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmClass" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmSection" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmSubjects" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="cmStaff">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cmStaffAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmAppointmentType" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmLeaveSructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="cmCalendar">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cmCalendarAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmSchoolCalendar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmClassCalendar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="cmTransport">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cmTransportAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmDriver" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmVehicle" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmRoute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="cmFinance">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cmFinanceAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmTuitionFeeStructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmOtherFeeStructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="cmLibrary">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cmLibraryAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmLibraryBooksCategory" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="cmLibraryBooksEntry" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cmAdministrator",
        "cmStaff",
        "cmCalendar",
        "cmTransport",
        "cmFinance",
        "cmLibrary"
    })
    public static class ConfigurationManagement {

        @XmlElement(required = true)
        protected SchoolAccess.ConfigurationManagement.CmAdministrator cmAdministrator;
        @XmlElement(required = true)
        protected SchoolAccess.ConfigurationManagement.CmStaff cmStaff;
        @XmlElement(required = true)
        protected SchoolAccess.ConfigurationManagement.CmCalendar cmCalendar;
        @XmlElement(required = true)
        protected SchoolAccess.ConfigurationManagement.CmTransport cmTransport;
        @XmlElement(required = true)
        protected SchoolAccess.ConfigurationManagement.CmFinance cmFinance;
        @XmlElement(required = true)
        protected SchoolAccess.ConfigurationManagement.CmLibrary cmLibrary;

        /**
         * Gets the value of the cmAdministrator property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.ConfigurationManagement.CmAdministrator }
         *     
         */
        public SchoolAccess.ConfigurationManagement.CmAdministrator getCmAdministrator() {
            return cmAdministrator;
        }

        /**
         * Sets the value of the cmAdministrator property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.ConfigurationManagement.CmAdministrator }
         *     
         */
        public void setCmAdministrator(SchoolAccess.ConfigurationManagement.CmAdministrator value) {
            this.cmAdministrator = value;
        }

        /**
         * Gets the value of the cmStaff property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.ConfigurationManagement.CmStaff }
         *     
         */
        public SchoolAccess.ConfigurationManagement.CmStaff getCmStaff() {
            return cmStaff;
        }

        /**
         * Sets the value of the cmStaff property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.ConfigurationManagement.CmStaff }
         *     
         */
        public void setCmStaff(SchoolAccess.ConfigurationManagement.CmStaff value) {
            this.cmStaff = value;
        }

        /**
         * Gets the value of the cmCalendar property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.ConfigurationManagement.CmCalendar }
         *     
         */
        public SchoolAccess.ConfigurationManagement.CmCalendar getCmCalendar() {
            return cmCalendar;
        }

        /**
         * Sets the value of the cmCalendar property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.ConfigurationManagement.CmCalendar }
         *     
         */
        public void setCmCalendar(SchoolAccess.ConfigurationManagement.CmCalendar value) {
            this.cmCalendar = value;
        }

        /**
         * Gets the value of the cmTransport property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.ConfigurationManagement.CmTransport }
         *     
         */
        public SchoolAccess.ConfigurationManagement.CmTransport getCmTransport() {
            return cmTransport;
        }

        /**
         * Sets the value of the cmTransport property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.ConfigurationManagement.CmTransport }
         *     
         */
        public void setCmTransport(SchoolAccess.ConfigurationManagement.CmTransport value) {
            this.cmTransport = value;
        }

        /**
         * Gets the value of the cmFinance property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.ConfigurationManagement.CmFinance }
         *     
         */
        public SchoolAccess.ConfigurationManagement.CmFinance getCmFinance() {
            return cmFinance;
        }

        /**
         * Sets the value of the cmFinance property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.ConfigurationManagement.CmFinance }
         *     
         */
        public void setCmFinance(SchoolAccess.ConfigurationManagement.CmFinance value) {
            this.cmFinance = value;
        }

        /**
         * Gets the value of the cmLibrary property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.ConfigurationManagement.CmLibrary }
         *     
         */
        public SchoolAccess.ConfigurationManagement.CmLibrary getCmLibrary() {
            return cmLibrary;
        }

        /**
         * Sets the value of the cmLibrary property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.ConfigurationManagement.CmLibrary }
         *     
         */
        public void setCmLibrary(SchoolAccess.ConfigurationManagement.CmLibrary value) {
            this.cmLibrary = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cmAdministratorAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmUserRole" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmClass" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmSection" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmSubjects" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cmAdministratorAccess",
            "cmUserRole",
            "cmClass",
            "cmSection",
            "cmSubjects"
        })
        public static class CmAdministrator {

            protected boolean cmAdministratorAccess;
            protected boolean cmUserRole;
            protected boolean cmClass;
            protected boolean cmSection;
            protected boolean cmSubjects;

            /**
             * Gets the value of the cmAdministratorAccess property.
             * 
             */
            public boolean isCmAdministratorAccess() {
                return cmAdministratorAccess;
            }

            /**
             * Sets the value of the cmAdministratorAccess property.
             * 
             */
            public void setCmAdministratorAccess(boolean value) {
                this.cmAdministratorAccess = value;
            }

            /**
             * Gets the value of the cmUserRole property.
             * 
             */
            public boolean isCmUserRole() {
                return cmUserRole;
            }

            /**
             * Sets the value of the cmUserRole property.
             * 
             */
            public void setCmUserRole(boolean value) {
                this.cmUserRole = value;
            }

            /**
             * Gets the value of the cmClass property.
             * 
             */
            public boolean isCmClass() {
                return cmClass;
            }

            /**
             * Sets the value of the cmClass property.
             * 
             */
            public void setCmClass(boolean value) {
                this.cmClass = value;
            }

            /**
             * Gets the value of the cmSection property.
             * 
             */
            public boolean isCmSection() {
                return cmSection;
            }

            /**
             * Sets the value of the cmSection property.
             * 
             */
            public void setCmSection(boolean value) {
                this.cmSection = value;
            }

            /**
             * Gets the value of the cmSubjects property.
             * 
             */
            public boolean isCmSubjects() {
                return cmSubjects;
            }

            /**
             * Sets the value of the cmSubjects property.
             * 
             */
            public void setCmSubjects(boolean value) {
                this.cmSubjects = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cmCalendarAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmSchoolCalendar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmClassCalendar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cmCalendarAccess",
            "cmSchoolCalendar",
            "cmClassCalendar"
        })
        public static class CmCalendar {

            protected boolean cmCalendarAccess;
            protected boolean cmSchoolCalendar;
            protected boolean cmClassCalendar;

            /**
             * Gets the value of the cmCalendarAccess property.
             * 
             */
            public boolean isCmCalendarAccess() {
                return cmCalendarAccess;
            }

            /**
             * Sets the value of the cmCalendarAccess property.
             * 
             */
            public void setCmCalendarAccess(boolean value) {
                this.cmCalendarAccess = value;
            }

            /**
             * Gets the value of the cmSchoolCalendar property.
             * 
             */
            public boolean isCmSchoolCalendar() {
                return cmSchoolCalendar;
            }

            /**
             * Sets the value of the cmSchoolCalendar property.
             * 
             */
            public void setCmSchoolCalendar(boolean value) {
                this.cmSchoolCalendar = value;
            }

            /**
             * Gets the value of the cmClassCalendar property.
             * 
             */
            public boolean isCmClassCalendar() {
                return cmClassCalendar;
            }

            /**
             * Sets the value of the cmClassCalendar property.
             * 
             */
            public void setCmClassCalendar(boolean value) {
                this.cmClassCalendar = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cmFinanceAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmTuitionFeeStructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmOtherFeeStructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cmFinanceAccess",
            "cmTuitionFeeStructure",
            "cmOtherFeeStructure"
        })
        public static class CmFinance {

            protected boolean cmFinanceAccess;
            protected boolean cmTuitionFeeStructure;
            protected boolean cmOtherFeeStructure;

            /**
             * Gets the value of the cmFinanceAccess property.
             * 
             */
            public boolean isCmFinanceAccess() {
                return cmFinanceAccess;
            }

            /**
             * Sets the value of the cmFinanceAccess property.
             * 
             */
            public void setCmFinanceAccess(boolean value) {
                this.cmFinanceAccess = value;
            }

            /**
             * Gets the value of the cmTuitionFeeStructure property.
             * 
             */
            public boolean isCmTuitionFeeStructure() {
                return cmTuitionFeeStructure;
            }

            /**
             * Sets the value of the cmTuitionFeeStructure property.
             * 
             */
            public void setCmTuitionFeeStructure(boolean value) {
                this.cmTuitionFeeStructure = value;
            }

            /**
             * Gets the value of the cmOtherFeeStructure property.
             * 
             */
            public boolean isCmOtherFeeStructure() {
                return cmOtherFeeStructure;
            }

            /**
             * Sets the value of the cmOtherFeeStructure property.
             * 
             */
            public void setCmOtherFeeStructure(boolean value) {
                this.cmOtherFeeStructure = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cmLibraryAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmLibraryBooksCategory" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmLibraryBooksEntry" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cmLibraryAccess",
            "cmLibraryBooksCategory",
            "cmLibraryBooksEntry"
        })
        public static class CmLibrary {

            protected boolean cmLibraryAccess;
            protected boolean cmLibraryBooksCategory;
            protected boolean cmLibraryBooksEntry;

            /**
             * Gets the value of the cmLibraryAccess property.
             * 
             */
            public boolean isCmLibraryAccess() {
                return cmLibraryAccess;
            }

            /**
             * Sets the value of the cmLibraryAccess property.
             * 
             */
            public void setCmLibraryAccess(boolean value) {
                this.cmLibraryAccess = value;
            }

            /**
             * Gets the value of the cmLibraryBooksCategory property.
             * 
             */
            public boolean isCmLibraryBooksCategory() {
                return cmLibraryBooksCategory;
            }

            /**
             * Sets the value of the cmLibraryBooksCategory property.
             * 
             */
            public void setCmLibraryBooksCategory(boolean value) {
                this.cmLibraryBooksCategory = value;
            }

            /**
             * Gets the value of the cmLibraryBooksEntry property.
             * 
             */
            public boolean isCmLibraryBooksEntry() {
                return cmLibraryBooksEntry;
            }

            /**
             * Sets the value of the cmLibraryBooksEntry property.
             * 
             */
            public void setCmLibraryBooksEntry(boolean value) {
                this.cmLibraryBooksEntry = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cmStaffAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmAppointmentType" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmLeaveSructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cmStaffAccess",
            "cmAppointmentType",
            "cmLeaveSructure"
        })
        public static class CmStaff {

            protected boolean cmStaffAccess;
            protected boolean cmAppointmentType;
            protected boolean cmLeaveSructure;

            /**
             * Gets the value of the cmStaffAccess property.
             * 
             */
            public boolean isCmStaffAccess() {
                return cmStaffAccess;
            }

            /**
             * Sets the value of the cmStaffAccess property.
             * 
             */
            public void setCmStaffAccess(boolean value) {
                this.cmStaffAccess = value;
            }

            /**
             * Gets the value of the cmAppointmentType property.
             * 
             */
            public boolean isCmAppointmentType() {
                return cmAppointmentType;
            }

            /**
             * Sets the value of the cmAppointmentType property.
             * 
             */
            public void setCmAppointmentType(boolean value) {
                this.cmAppointmentType = value;
            }

            /**
             * Gets the value of the cmLeaveSructure property.
             * 
             */
            public boolean isCmLeaveSructure() {
                return cmLeaveSructure;
            }

            /**
             * Sets the value of the cmLeaveSructure property.
             * 
             */
            public void setCmLeaveSructure(boolean value) {
                this.cmLeaveSructure = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cmTransportAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmDriver" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmVehicle" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="cmRoute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cmTransportAccess",
            "cmDriver",
            "cmVehicle",
            "cmRoute"
        })
        public static class CmTransport {

            protected boolean cmTransportAccess;
            protected boolean cmDriver;
            protected boolean cmVehicle;
            protected boolean cmRoute;

            /**
             * Gets the value of the cmTransportAccess property.
             * 
             */
            public boolean isCmTransportAccess() {
                return cmTransportAccess;
            }

            /**
             * Sets the value of the cmTransportAccess property.
             * 
             */
            public void setCmTransportAccess(boolean value) {
                this.cmTransportAccess = value;
            }

            /**
             * Gets the value of the cmDriver property.
             * 
             */
            public boolean isCmDriver() {
                return cmDriver;
            }

            /**
             * Sets the value of the cmDriver property.
             * 
             */
            public void setCmDriver(boolean value) {
                this.cmDriver = value;
            }

            /**
             * Gets the value of the cmVehicle property.
             * 
             */
            public boolean isCmVehicle() {
                return cmVehicle;
            }

            /**
             * Sets the value of the cmVehicle property.
             * 
             */
            public void setCmVehicle(boolean value) {
                this.cmVehicle = value;
            }

            /**
             * Gets the value of the cmRoute property.
             * 
             */
            public boolean isCmRoute() {
                return cmRoute;
            }

            /**
             * Sets the value of the cmRoute property.
             * 
             */
            public void setCmRoute(boolean value) {
                this.cmRoute = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fmAdministrator">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fmAdministratorAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmUser" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmStaff" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmStudent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmRollNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fmLeaves">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fmLeavesAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmStudentLeaves" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmStaffLeaves" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fmCommunication">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fmCommunicationAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmSchedule" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmHolidays" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmSms" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fmTransportation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fmTransportationAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmTransportationRoute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fmFinance">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fmFinanceAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmTuitionFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmOtherFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fmLibrary">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fmLibraryAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmBooks" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fmReports">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fmReportsAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmStudentReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmStaffReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmClassReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmSchoolReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fmAvailability">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fmAvailabilityAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="fmAvailabilityCheck" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fmAdministrator",
        "fmLeaves",
        "fmCommunication",
        "fmTransportation",
        "fmFinance",
        "fmLibrary",
        "fmReports",
        "fmAvailability"
    })
    public static class FunctionalManagement {

        @XmlElement(required = true)
        protected SchoolAccess.FunctionalManagement.FmAdministrator fmAdministrator;
        @XmlElement(required = true)
        protected SchoolAccess.FunctionalManagement.FmLeaves fmLeaves;
        @XmlElement(required = true)
        protected SchoolAccess.FunctionalManagement.FmCommunication fmCommunication;
        @XmlElement(required = true)
        protected SchoolAccess.FunctionalManagement.FmTransportation fmTransportation;
        @XmlElement(required = true)
        protected SchoolAccess.FunctionalManagement.FmFinance fmFinance;
        @XmlElement(required = true)
        protected SchoolAccess.FunctionalManagement.FmLibrary fmLibrary;
        @XmlElement(required = true)
        protected SchoolAccess.FunctionalManagement.FmReports fmReports;
        @XmlElement(required = true)
        protected SchoolAccess.FunctionalManagement.FmAvailability fmAvailability;

        /**
         * Gets the value of the fmAdministrator property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.FunctionalManagement.FmAdministrator }
         *     
         */
        public SchoolAccess.FunctionalManagement.FmAdministrator getFmAdministrator() {
            return fmAdministrator;
        }

        /**
         * Sets the value of the fmAdministrator property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.FunctionalManagement.FmAdministrator }
         *     
         */
        public void setFmAdministrator(SchoolAccess.FunctionalManagement.FmAdministrator value) {
            this.fmAdministrator = value;
        }

        /**
         * Gets the value of the fmLeaves property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.FunctionalManagement.FmLeaves }
         *     
         */
        public SchoolAccess.FunctionalManagement.FmLeaves getFmLeaves() {
            return fmLeaves;
        }

        /**
         * Sets the value of the fmLeaves property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.FunctionalManagement.FmLeaves }
         *     
         */
        public void setFmLeaves(SchoolAccess.FunctionalManagement.FmLeaves value) {
            this.fmLeaves = value;
        }

        /**
         * Gets the value of the fmCommunication property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.FunctionalManagement.FmCommunication }
         *     
         */
        public SchoolAccess.FunctionalManagement.FmCommunication getFmCommunication() {
            return fmCommunication;
        }

        /**
         * Sets the value of the fmCommunication property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.FunctionalManagement.FmCommunication }
         *     
         */
        public void setFmCommunication(SchoolAccess.FunctionalManagement.FmCommunication value) {
            this.fmCommunication = value;
        }

        /**
         * Gets the value of the fmTransportation property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.FunctionalManagement.FmTransportation }
         *     
         */
        public SchoolAccess.FunctionalManagement.FmTransportation getFmTransportation() {
            return fmTransportation;
        }

        /**
         * Sets the value of the fmTransportation property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.FunctionalManagement.FmTransportation }
         *     
         */
        public void setFmTransportation(SchoolAccess.FunctionalManagement.FmTransportation value) {
            this.fmTransportation = value;
        }

        /**
         * Gets the value of the fmFinance property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.FunctionalManagement.FmFinance }
         *     
         */
        public SchoolAccess.FunctionalManagement.FmFinance getFmFinance() {
            return fmFinance;
        }

        /**
         * Sets the value of the fmFinance property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.FunctionalManagement.FmFinance }
         *     
         */
        public void setFmFinance(SchoolAccess.FunctionalManagement.FmFinance value) {
            this.fmFinance = value;
        }

        /**
         * Gets the value of the fmLibrary property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.FunctionalManagement.FmLibrary }
         *     
         */
        public SchoolAccess.FunctionalManagement.FmLibrary getFmLibrary() {
            return fmLibrary;
        }

        /**
         * Sets the value of the fmLibrary property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.FunctionalManagement.FmLibrary }
         *     
         */
        public void setFmLibrary(SchoolAccess.FunctionalManagement.FmLibrary value) {
            this.fmLibrary = value;
        }

        /**
         * Gets the value of the fmReports property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.FunctionalManagement.FmReports }
         *     
         */
        public SchoolAccess.FunctionalManagement.FmReports getFmReports() {
            return fmReports;
        }

        /**
         * Sets the value of the fmReports property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.FunctionalManagement.FmReports }
         *     
         */
        public void setFmReports(SchoolAccess.FunctionalManagement.FmReports value) {
            this.fmReports = value;
        }

        /**
         * Gets the value of the fmAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link SchoolAccess.FunctionalManagement.FmAvailability }
         *     
         */
        public SchoolAccess.FunctionalManagement.FmAvailability getFmAvailability() {
            return fmAvailability;
        }

        /**
         * Sets the value of the fmAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchoolAccess.FunctionalManagement.FmAvailability }
         *     
         */
        public void setFmAvailability(SchoolAccess.FunctionalManagement.FmAvailability value) {
            this.fmAvailability = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fmAdministratorAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmUser" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmStaff" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmStudent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmRollNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fmAdministratorAccess",
            "fmUser",
            "fmStaff",
            "fmStudent",
            "fmRollNumber"
        })
        public static class FmAdministrator {

            protected boolean fmAdministratorAccess;
            protected boolean fmUser;
            protected boolean fmStaff;
            protected boolean fmStudent;
            protected boolean fmRollNumber;

            /**
             * Gets the value of the fmAdministratorAccess property.
             * 
             */
            public boolean isFmAdministratorAccess() {
                return fmAdministratorAccess;
            }

            /**
             * Sets the value of the fmAdministratorAccess property.
             * 
             */
            public void setFmAdministratorAccess(boolean value) {
                this.fmAdministratorAccess = value;
            }

            /**
             * Gets the value of the fmUser property.
             * 
             */
            public boolean isFmUser() {
                return fmUser;
            }

            /**
             * Sets the value of the fmUser property.
             * 
             */
            public void setFmUser(boolean value) {
                this.fmUser = value;
            }

            /**
             * Gets the value of the fmStaff property.
             * 
             */
            public boolean isFmStaff() {
                return fmStaff;
            }

            /**
             * Sets the value of the fmStaff property.
             * 
             */
            public void setFmStaff(boolean value) {
                this.fmStaff = value;
            }

            /**
             * Gets the value of the fmStudent property.
             * 
             */
            public boolean isFmStudent() {
                return fmStudent;
            }

            /**
             * Sets the value of the fmStudent property.
             * 
             */
            public void setFmStudent(boolean value) {
                this.fmStudent = value;
            }

            /**
             * Gets the value of the fmRollNumber property.
             * 
             */
            public boolean isFmRollNumber() {
                return fmRollNumber;
            }

            /**
             * Sets the value of the fmRollNumber property.
             * 
             */
            public void setFmRollNumber(boolean value) {
                this.fmRollNumber = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fmAvailabilityAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmAvailabilityCheck" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fmAvailabilityAccess",
            "fmAvailabilityCheck"
        })
        public static class FmAvailability {

            protected boolean fmAvailabilityAccess;
            protected boolean fmAvailabilityCheck;

            /**
             * Gets the value of the fmAvailabilityAccess property.
             * 
             */
            public boolean isFmAvailabilityAccess() {
                return fmAvailabilityAccess;
            }

            /**
             * Sets the value of the fmAvailabilityAccess property.
             * 
             */
            public void setFmAvailabilityAccess(boolean value) {
                this.fmAvailabilityAccess = value;
            }

            /**
             * Gets the value of the fmAvailabilityCheck property.
             * 
             */
            public boolean isFmAvailabilityCheck() {
                return fmAvailabilityCheck;
            }

            /**
             * Sets the value of the fmAvailabilityCheck property.
             * 
             */
            public void setFmAvailabilityCheck(boolean value) {
                this.fmAvailabilityCheck = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fmCommunicationAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmSchedule" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmHolidays" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmSms" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fmCommunicationAccess",
            "fmSchedule",
            "fmHolidays",
            "fmSms"
        })
        public static class FmCommunication {

            protected boolean fmCommunicationAccess;
            protected boolean fmSchedule;
            protected boolean fmHolidays;
            protected boolean fmSms;

            /**
             * Gets the value of the fmCommunicationAccess property.
             * 
             */
            public boolean isFmCommunicationAccess() {
                return fmCommunicationAccess;
            }

            /**
             * Sets the value of the fmCommunicationAccess property.
             * 
             */
            public void setFmCommunicationAccess(boolean value) {
                this.fmCommunicationAccess = value;
            }

            /**
             * Gets the value of the fmSchedule property.
             * 
             */
            public boolean isFmSchedule() {
                return fmSchedule;
            }

            /**
             * Sets the value of the fmSchedule property.
             * 
             */
            public void setFmSchedule(boolean value) {
                this.fmSchedule = value;
            }

            /**
             * Gets the value of the fmHolidays property.
             * 
             */
            public boolean isFmHolidays() {
                return fmHolidays;
            }

            /**
             * Sets the value of the fmHolidays property.
             * 
             */
            public void setFmHolidays(boolean value) {
                this.fmHolidays = value;
            }

            /**
             * Gets the value of the fmSms property.
             * 
             */
            public boolean isFmSms() {
                return fmSms;
            }

            /**
             * Sets the value of the fmSms property.
             * 
             */
            public void setFmSms(boolean value) {
                this.fmSms = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fmFinanceAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmTuitionFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmOtherFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fmFinanceAccess",
            "fmTuitionFee",
            "fmOtherFee"
        })
        public static class FmFinance {

            protected boolean fmFinanceAccess;
            protected boolean fmTuitionFee;
            protected boolean fmOtherFee;

            /**
             * Gets the value of the fmFinanceAccess property.
             * 
             */
            public boolean isFmFinanceAccess() {
                return fmFinanceAccess;
            }

            /**
             * Sets the value of the fmFinanceAccess property.
             * 
             */
            public void setFmFinanceAccess(boolean value) {
                this.fmFinanceAccess = value;
            }

            /**
             * Gets the value of the fmTuitionFee property.
             * 
             */
            public boolean isFmTuitionFee() {
                return fmTuitionFee;
            }

            /**
             * Sets the value of the fmTuitionFee property.
             * 
             */
            public void setFmTuitionFee(boolean value) {
                this.fmTuitionFee = value;
            }

            /**
             * Gets the value of the fmOtherFee property.
             * 
             */
            public boolean isFmOtherFee() {
                return fmOtherFee;
            }

            /**
             * Sets the value of the fmOtherFee property.
             * 
             */
            public void setFmOtherFee(boolean value) {
                this.fmOtherFee = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fmLeavesAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmStudentLeaves" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmStaffLeaves" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fmLeavesAccess",
            "fmStudentLeaves",
            "fmStaffLeaves"
        })
        public static class FmLeaves {

            protected boolean fmLeavesAccess;
            protected boolean fmStudentLeaves;
            protected boolean fmStaffLeaves;

            /**
             * Gets the value of the fmLeavesAccess property.
             * 
             */
            public boolean isFmLeavesAccess() {
                return fmLeavesAccess;
            }

            /**
             * Sets the value of the fmLeavesAccess property.
             * 
             */
            public void setFmLeavesAccess(boolean value) {
                this.fmLeavesAccess = value;
            }

            /**
             * Gets the value of the fmStudentLeaves property.
             * 
             */
            public boolean isFmStudentLeaves() {
                return fmStudentLeaves;
            }

            /**
             * Sets the value of the fmStudentLeaves property.
             * 
             */
            public void setFmStudentLeaves(boolean value) {
                this.fmStudentLeaves = value;
            }

            /**
             * Gets the value of the fmStaffLeaves property.
             * 
             */
            public boolean isFmStaffLeaves() {
                return fmStaffLeaves;
            }

            /**
             * Sets the value of the fmStaffLeaves property.
             * 
             */
            public void setFmStaffLeaves(boolean value) {
                this.fmStaffLeaves = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fmLibraryAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmBooks" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fmLibraryAccess",
            "fmBooks"
        })
        public static class FmLibrary {

            protected boolean fmLibraryAccess;
            protected boolean fmBooks;

            /**
             * Gets the value of the fmLibraryAccess property.
             * 
             */
            public boolean isFmLibraryAccess() {
                return fmLibraryAccess;
            }

            /**
             * Sets the value of the fmLibraryAccess property.
             * 
             */
            public void setFmLibraryAccess(boolean value) {
                this.fmLibraryAccess = value;
            }

            /**
             * Gets the value of the fmBooks property.
             * 
             */
            public boolean isFmBooks() {
                return fmBooks;
            }

            /**
             * Sets the value of the fmBooks property.
             * 
             */
            public void setFmBooks(boolean value) {
                this.fmBooks = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fmReportsAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmStudentReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmStaffReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmClassReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmSchoolReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fmReportsAccess",
            "fmStudentReports",
            "fmStaffReports",
            "fmClassReports",
            "fmSchoolReports"
        })
        public static class FmReports {

            protected boolean fmReportsAccess;
            protected boolean fmStudentReports;
            protected boolean fmStaffReports;
            protected boolean fmClassReports;
            protected boolean fmSchoolReports;

            /**
             * Gets the value of the fmReportsAccess property.
             * 
             */
            public boolean isFmReportsAccess() {
                return fmReportsAccess;
            }

            /**
             * Sets the value of the fmReportsAccess property.
             * 
             */
            public void setFmReportsAccess(boolean value) {
                this.fmReportsAccess = value;
            }

            /**
             * Gets the value of the fmStudentReports property.
             * 
             */
            public boolean isFmStudentReports() {
                return fmStudentReports;
            }

            /**
             * Sets the value of the fmStudentReports property.
             * 
             */
            public void setFmStudentReports(boolean value) {
                this.fmStudentReports = value;
            }

            /**
             * Gets the value of the fmStaffReports property.
             * 
             */
            public boolean isFmStaffReports() {
                return fmStaffReports;
            }

            /**
             * Sets the value of the fmStaffReports property.
             * 
             */
            public void setFmStaffReports(boolean value) {
                this.fmStaffReports = value;
            }

            /**
             * Gets the value of the fmClassReports property.
             * 
             */
            public boolean isFmClassReports() {
                return fmClassReports;
            }

            /**
             * Sets the value of the fmClassReports property.
             * 
             */
            public void setFmClassReports(boolean value) {
                this.fmClassReports = value;
            }

            /**
             * Gets the value of the fmSchoolReports property.
             * 
             */
            public boolean isFmSchoolReports() {
                return fmSchoolReports;
            }

            /**
             * Sets the value of the fmSchoolReports property.
             * 
             */
            public void setFmSchoolReports(boolean value) {
                this.fmSchoolReports = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fmTransportationAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="fmTransportationRoute" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fmTransportationAccess",
            "fmTransportationRoute"
        })
        public static class FmTransportation {

            protected boolean fmTransportationAccess;
            protected boolean fmTransportationRoute;

            /**
             * Gets the value of the fmTransportationAccess property.
             * 
             */
            public boolean isFmTransportationAccess() {
                return fmTransportationAccess;
            }

            /**
             * Sets the value of the fmTransportationAccess property.
             * 
             */
            public void setFmTransportationAccess(boolean value) {
                this.fmTransportationAccess = value;
            }

            /**
             * Gets the value of the fmTransportationRoute property.
             * 
             */
            public boolean isFmTransportationRoute() {
                return fmTransportationRoute;
            }

            /**
             * Sets the value of the fmTransportationRoute property.
             * 
             */
            public void setFmTransportationRoute(boolean value) {
                this.fmTransportationRoute = value;
            }

        }

    }

}
