//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 11:44:22 PM IST 
//


package com.myschool.userLevelAccess;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.myschool.userLevelAccess package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.myschool.userLevelAccess
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserLevelAccess }
     * 
     */
    public UserLevelAccess createUserLevelAccess() {
        return new UserLevelAccess();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement }
     * 
     */
    public UserLevelAccess.FunctionalManagement createUserLevelAccessFunctionalManagement() {
        return new UserLevelAccess.FunctionalManagement();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmAvailability }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmAvailability createUserLevelAccessFunctionalManagementFmAvailability() {
        return new UserLevelAccess.FunctionalManagement.FmAvailability();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmReports }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmReports createUserLevelAccessFunctionalManagementFmReports() {
        return new UserLevelAccess.FunctionalManagement.FmReports();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmLibrary }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmLibrary createUserLevelAccessFunctionalManagementFmLibrary() {
        return new UserLevelAccess.FunctionalManagement.FmLibrary();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmFinance }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmFinance createUserLevelAccessFunctionalManagementFmFinance() {
        return new UserLevelAccess.FunctionalManagement.FmFinance();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmTransportation }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmTransportation createUserLevelAccessFunctionalManagementFmTransportation() {
        return new UserLevelAccess.FunctionalManagement.FmTransportation();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmCommunication }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmCommunication createUserLevelAccessFunctionalManagementFmCommunication() {
        return new UserLevelAccess.FunctionalManagement.FmCommunication();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmLeaves }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmLeaves createUserLevelAccessFunctionalManagementFmLeaves() {
        return new UserLevelAccess.FunctionalManagement.FmLeaves();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmAdministrator }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmAdministrator createUserLevelAccessFunctionalManagementFmAdministrator() {
        return new UserLevelAccess.FunctionalManagement.FmAdministrator();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement }
     * 
     */
    public UserLevelAccess.ConfigurationManagement createUserLevelAccessConfigurationManagement() {
        return new UserLevelAccess.ConfigurationManagement();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmLibrary }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmLibrary createUserLevelAccessConfigurationManagementCmLibrary() {
        return new UserLevelAccess.ConfigurationManagement.CmLibrary();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmFinance }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmFinance createUserLevelAccessConfigurationManagementCmFinance() {
        return new UserLevelAccess.ConfigurationManagement.CmFinance();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmTransport }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmTransport createUserLevelAccessConfigurationManagementCmTransport() {
        return new UserLevelAccess.ConfigurationManagement.CmTransport();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmCalendar }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmCalendar createUserLevelAccessConfigurationManagementCmCalendar() {
        return new UserLevelAccess.ConfigurationManagement.CmCalendar();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmStaff }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmStaff createUserLevelAccessConfigurationManagementCmStaff() {
        return new UserLevelAccess.ConfigurationManagement.CmStaff();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmAdministrator }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmAdministrator createUserLevelAccessConfigurationManagementCmAdministrator() {
        return new UserLevelAccess.ConfigurationManagement.CmAdministrator();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmAvailability.FmAvailabilityCheck }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmAvailability.FmAvailabilityCheck createUserLevelAccessFunctionalManagementFmAvailabilityFmAvailabilityCheck() {
        return new UserLevelAccess.FunctionalManagement.FmAvailability.FmAvailabilityCheck();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmReports.FmStudentReports }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmReports.FmStudentReports createUserLevelAccessFunctionalManagementFmReportsFmStudentReports() {
        return new UserLevelAccess.FunctionalManagement.FmReports.FmStudentReports();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmReports.FmStaffReports }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmReports.FmStaffReports createUserLevelAccessFunctionalManagementFmReportsFmStaffReports() {
        return new UserLevelAccess.FunctionalManagement.FmReports.FmStaffReports();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmReports.FmClassReports }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmReports.FmClassReports createUserLevelAccessFunctionalManagementFmReportsFmClassReports() {
        return new UserLevelAccess.FunctionalManagement.FmReports.FmClassReports();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmReports.FmSchoolReports }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmReports.FmSchoolReports createUserLevelAccessFunctionalManagementFmReportsFmSchoolReports() {
        return new UserLevelAccess.FunctionalManagement.FmReports.FmSchoolReports();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmLibrary.FmBooks }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmLibrary.FmBooks createUserLevelAccessFunctionalManagementFmLibraryFmBooks() {
        return new UserLevelAccess.FunctionalManagement.FmLibrary.FmBooks();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmFinance.FmTuitionFee }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmFinance.FmTuitionFee createUserLevelAccessFunctionalManagementFmFinanceFmTuitionFee() {
        return new UserLevelAccess.FunctionalManagement.FmFinance.FmTuitionFee();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmFinance.FmOtherFee }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmFinance.FmOtherFee createUserLevelAccessFunctionalManagementFmFinanceFmOtherFee() {
        return new UserLevelAccess.FunctionalManagement.FmFinance.FmOtherFee();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmTransportation.FmTransportationRoute }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmTransportation.FmTransportationRoute createUserLevelAccessFunctionalManagementFmTransportationFmTransportationRoute() {
        return new UserLevelAccess.FunctionalManagement.FmTransportation.FmTransportationRoute();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmCommunication.FmSchedule }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmCommunication.FmSchedule createUserLevelAccessFunctionalManagementFmCommunicationFmSchedule() {
        return new UserLevelAccess.FunctionalManagement.FmCommunication.FmSchedule();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmCommunication.FmHolidays }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmCommunication.FmHolidays createUserLevelAccessFunctionalManagementFmCommunicationFmHolidays() {
        return new UserLevelAccess.FunctionalManagement.FmCommunication.FmHolidays();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmCommunication.FmSms }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmCommunication.FmSms createUserLevelAccessFunctionalManagementFmCommunicationFmSms() {
        return new UserLevelAccess.FunctionalManagement.FmCommunication.FmSms();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmLeaves.FmStudentLeaves }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmLeaves.FmStudentLeaves createUserLevelAccessFunctionalManagementFmLeavesFmStudentLeaves() {
        return new UserLevelAccess.FunctionalManagement.FmLeaves.FmStudentLeaves();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmLeaves.FmStaffLeaves }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmLeaves.FmStaffLeaves createUserLevelAccessFunctionalManagementFmLeavesFmStaffLeaves() {
        return new UserLevelAccess.FunctionalManagement.FmLeaves.FmStaffLeaves();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmAdministrator.FmUser }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmAdministrator.FmUser createUserLevelAccessFunctionalManagementFmAdministratorFmUser() {
        return new UserLevelAccess.FunctionalManagement.FmAdministrator.FmUser();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmAdministrator.FmStaff }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmAdministrator.FmStaff createUserLevelAccessFunctionalManagementFmAdministratorFmStaff() {
        return new UserLevelAccess.FunctionalManagement.FmAdministrator.FmStaff();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmAdministrator.FmStudent }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmAdministrator.FmStudent createUserLevelAccessFunctionalManagementFmAdministratorFmStudent() {
        return new UserLevelAccess.FunctionalManagement.FmAdministrator.FmStudent();
    }

    /**
     * Create an instance of {@link UserLevelAccess.FunctionalManagement.FmAdministrator.FmRollNumber }
     * 
     */
    public UserLevelAccess.FunctionalManagement.FmAdministrator.FmRollNumber createUserLevelAccessFunctionalManagementFmAdministratorFmRollNumber() {
        return new UserLevelAccess.FunctionalManagement.FmAdministrator.FmRollNumber();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmLibrary.CmLibraryBooksCategory }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmLibrary.CmLibraryBooksCategory createUserLevelAccessConfigurationManagementCmLibraryCmLibraryBooksCategory() {
        return new UserLevelAccess.ConfigurationManagement.CmLibrary.CmLibraryBooksCategory();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmLibrary.CmLibraryBooksEntry }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmLibrary.CmLibraryBooksEntry createUserLevelAccessConfigurationManagementCmLibraryCmLibraryBooksEntry() {
        return new UserLevelAccess.ConfigurationManagement.CmLibrary.CmLibraryBooksEntry();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmFinance.CmTuitionFeeStructure }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmFinance.CmTuitionFeeStructure createUserLevelAccessConfigurationManagementCmFinanceCmTuitionFeeStructure() {
        return new UserLevelAccess.ConfigurationManagement.CmFinance.CmTuitionFeeStructure();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmFinance.CmOtherFeeStructure }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmFinance.CmOtherFeeStructure createUserLevelAccessConfigurationManagementCmFinanceCmOtherFeeStructure() {
        return new UserLevelAccess.ConfigurationManagement.CmFinance.CmOtherFeeStructure();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmTransport.CmDriver }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmTransport.CmDriver createUserLevelAccessConfigurationManagementCmTransportCmDriver() {
        return new UserLevelAccess.ConfigurationManagement.CmTransport.CmDriver();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmTransport.CmVehicle }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmTransport.CmVehicle createUserLevelAccessConfigurationManagementCmTransportCmVehicle() {
        return new UserLevelAccess.ConfigurationManagement.CmTransport.CmVehicle();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmTransport.CmRoute }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmTransport.CmRoute createUserLevelAccessConfigurationManagementCmTransportCmRoute() {
        return new UserLevelAccess.ConfigurationManagement.CmTransport.CmRoute();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmCalendar.CmSchoolCalendar }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmCalendar.CmSchoolCalendar createUserLevelAccessConfigurationManagementCmCalendarCmSchoolCalendar() {
        return new UserLevelAccess.ConfigurationManagement.CmCalendar.CmSchoolCalendar();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmCalendar.CmClassCalendar }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmCalendar.CmClassCalendar createUserLevelAccessConfigurationManagementCmCalendarCmClassCalendar() {
        return new UserLevelAccess.ConfigurationManagement.CmCalendar.CmClassCalendar();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmStaff.CmAppointmentType }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmStaff.CmAppointmentType createUserLevelAccessConfigurationManagementCmStaffCmAppointmentType() {
        return new UserLevelAccess.ConfigurationManagement.CmStaff.CmAppointmentType();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmStaff.CmLeaveSructure }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmStaff.CmLeaveSructure createUserLevelAccessConfigurationManagementCmStaffCmLeaveSructure() {
        return new UserLevelAccess.ConfigurationManagement.CmStaff.CmLeaveSructure();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmAdministrator.CmUser }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmAdministrator.CmUser createUserLevelAccessConfigurationManagementCmAdministratorCmUser() {
        return new UserLevelAccess.ConfigurationManagement.CmAdministrator.CmUser();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmAdministrator.CmClass }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmAdministrator.CmClass createUserLevelAccessConfigurationManagementCmAdministratorCmClass() {
        return new UserLevelAccess.ConfigurationManagement.CmAdministrator.CmClass();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmAdministrator.CmSection }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmAdministrator.CmSection createUserLevelAccessConfigurationManagementCmAdministratorCmSection() {
        return new UserLevelAccess.ConfigurationManagement.CmAdministrator.CmSection();
    }

    /**
     * Create an instance of {@link UserLevelAccess.ConfigurationManagement.CmAdministrator.CmSubjects }
     * 
     */
    public UserLevelAccess.ConfigurationManagement.CmAdministrator.CmSubjects createUserLevelAccessConfigurationManagementCmAdministratorCmSubjects() {
        return new UserLevelAccess.ConfigurationManagement.CmAdministrator.CmSubjects();
    }

}
