  CREATE TABLE "SCHOOL"."USER_DETAILS" 
   (	"USER_DETAIS_ID" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(60 BYTE), 
	"USER_ROLE_ID" NUMBER(2,0) NOT NULL ENABLE, 
	"USER_FIRST_NAME" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"USER_MIDDLE_NAME" VARCHAR2(25 BYTE), 
	"USER_LAST_NAME" VARCHAR2(25 BYTE), 
	"USER_DOB" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"USER_GENDER" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"USER_STATUS" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"CHANGE_PASSWORD_QUESTION" VARCHAR2(90 BYTE) NOT NULL ENABLE, 
	"CHANGE_PASSWORD_ANSWER" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"CREATED_USER_ID" VARCHAR2(12 BYTE), 
	"MODIFIED_USER_ID" VARCHAR2(12 BYTE), 
	"CREATED_DATE_AND_TIME" TIMESTAMP (2) WITH TIME ZONE, 
	"MODIFIED_DATE_AND_TIME" TIMESTAMP (2) WITH TIME ZONE, 
	 CONSTRAINT "USER_NAME PK" PRIMARY KEY ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "USER_GENDER_CHK1" CHECK (
USER_GENDER IN ('MALE', 'FEMALE')
) ENABLE, 
	 CONSTRAINT "USER_STATUS_CHK1" CHECK (
USER_STATUS IN ('ACTIVE', 'NOT_ACTIVE')
) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  /
  